### ISSUE TITLE
Error with sidebar showing

### ISSUE THREAD

**Issue by GreyScales** [miton18/sql-display#2]
The sidebar has a visual error when split is active.
I have Brackets SASS, Emmet, Brackets Font, and Minimap installed.
You can see the error in the top left, the text is halved.

![screenshot 3](https://cloud.githubusercontent.com/assets/5384929/11027323/341e5b12-8682-11e5-9a24-d72598e8e564.png)

**Comment by miton18** [comment]
yes I saw, I have the same problem,  and sorry I haven t take the time to fix it
